### ISSUE TITLE
Option to open gmail's simplified HTML version

### ISSUE THREAD

**Issue by relaxeaza** [xavierfoucrier/inbox-notifier#160]
Would it be possible? All it need is to add `/h/` to the url.

**Comment by xavierfoucrier** [comment]
Hi @relaxeaza!

First of all, thank you for taking time to open an issue.

As I am using the "standard" version of Gmail, I had never think about adding this feature to the application but yes, it could be possible through a **custom property** in the notification behavior setting.

I will add this feature in the v3.0 :wink:
