### ISSUE TITLE
Vacation setting support

### ISSUE THREAD

**Issue by xavierfoucrier** [xavierfoucrier/inbox-notifier#171]
Allow the user to define if the application **take care of the Gmail vacation settings**: if enable, all notifications will be paused and the behavior will be the same as when scheduled synchronization is disabled. See https://developers.google.com/gmail/api/v1/reference/users/settings/getVacation.

> Note that the scheduler settings will override this feature when enabled.

**Comment by xavierfoucrier** [comment]
This will be implemented as a "built-in" feature and will automatically take care about the Gmail vacation setting.

> The feature will probably evolve, in a next version, into a dedicated tab to allow the user to customize the start/end date and other automatic reply settings

**Comment by fakeclubsoda** [comment]
Hi!

IMHO, you’re incorporating too many features. This program’s charm has always been its simplicity and minimalism. Why would we want to manage vacation settings through the notifier? Its job is to notify us about new email.

Nonetheless, thank you again for developing it. Can’t wait for the new Google-certified release!

fakeclubsoda

PS. Please keep the program alive on Windows 7 SP1 for as long as possible... Thank you!

**Comment by xavierfoucrier** [comment]
Hi @fakeclubsoda,

Thanks for your feedback, I really appreciate it!

As a creative developer, I got a lot of idea **everyday**, so I take care to think about the usefulness of all new features before adding it to Github, and finally, I always implement features that will improve my workflow and productivity.

The **vacation setting** is based on the `automatic reply` setting that you can find in the Gmail web interface and allow you to define if you are busy during a certain time, like when you are going to be on holidays, or leaving the office for a training, etc..

Using this setting will prevent the application from syncing the inbox during this laps of time, keeping you away from any notifications, and skip synchronization requests to save bandwidth and resources.

> This is useful only in case your computer is not in sleep mode during this laps of time

As I am a pro Windows 7 user, I will do my best to **keep the application compatible** with this operating system as long as I can.

Can't wait to see the app Google certified too.
Thanks again for your feedback :wink:

**Comment by fakeclubsoda** [comment]
Oh, so this is merely about preventing the application from syncing when Gmail’s vacation responder is activated. Sounds useful. I apologize for my earlier comment.

Thank you for the reassurance about Win7 compatibility.

So, now all we can do is wait for Google to give the program a ‘go-ahead’.

Thanks for keeping us posted Xavier.

**Comment by xavierfoucrier** [comment]
@fakeclubsoda don't worry, feedback are always useful here. :wink:

**Comment by xavierfoucrier** [comment]
After a bunch of tests, checking the vacation setting **slow down the synchronization process by adding a request on each synchronization tick**, as the parameter is stored server-side, especially when it is disabled: because the application need to know when it is useful to prevent notifications...

Finally, this feature won't be implemented.

> Good ideas are not always good to implement: that's why it's useful to test it in dev mode :sweat_smile:
