### ISSUE TITLE
Sync failure after session wake up

### ISSUE THREAD

**Issue by XtroTheArctic** [xavierfoucrier/inbox-notifier#205]
After PC wakes up, it makes a successful check only ones, then it stops checking completely.

In the screenshot, you can see that the check duration is set to 1 minute. The last check time is 10:46 which is the time I woke the PC up. Now the time has past 10:47 but it's not checking anymore.

It starts checking properly only after I restart the app.

![image](https://user-images.githubusercontent.com/6631429/168340298-cb9046f3-83e2-4794-b99f-5c657883e5fb.png)

**Comment by xavierfoucrier** [comment]
Hi @XtroTheArctic,

Thanks for reporting this.
Can you tell me if you paused the synchronization before your session goes to sleep mode?

> Anyway, I will investigate on this as soon as possible.

**Comment by XtroTheArctic** [comment]
No. This is the default behavior and it happens always. I didn't even know I could pause the synchronization.

**Comment by xavierfoucrier** [comment]
Thanks, I will investigate.

**Comment by XtroTheArctic** [comment]
I have a test finding about this.

While looking at the code, I noticed that you set UI.timer.Enabled to true only when this happens: target.Reason == SessionSwitchReason.SessionUnlock

Then I tried this. Woke the computer up from sleep, checked the last update time to make sure it is suspended.
Locked the computer manually and unlocked it.
Checked the last update and saw that it started working fine after unlocking the computer.

Looks like you need to set UI.timer.Enabled to true when the computer wakes up too because not all users use the lock screen after waking up the computer.

**Comment by XtroTheArctic** [comment]
I added this line in Computer.BindPowerMode method in my fork repo and it fixed the problem for me.

```
				else if (target.Mode == PowerModes.Resume) UI.timer.Enabled = true;
```

**Comment by xavierfoucrier** [comment]
@XtroTheArctic Thanks for investigating.

There are a lot of things to take into consideration, not only the lock screen.
I take the time to investigate.
