### ISSUE TITLE
Add an option to open the inbox when clicking the notification

### ISSUE THREAD

**Issue by XtroTheArctic** [xavierfoucrier/inbox-notifier#207]
![image](https://user-images.githubusercontent.com/6631429/168343467-e60cecd9-f83b-4f0e-b9b6-d5c253d0d049.png)

**Comment by xavierfoucrier** [comment]
Good idea @XtroTheArctic :wink:

**Comment by XtroTheArctic** [comment]
As I wrote in my last email to you, it may be better to add this option to General/Interface section because this Notification/Behavior section is related to the notifications; not the systray icon.
