### ISSUE TITLE
Add support for multiple Gmail accounts

### ISSUE THREAD

**Issue by rollecode** [xavierfoucrier/inbox-notifier#209]
Is it possible to add more than one Gmail account? I'm using two Gmail accounts, both are improtant.

**Comment by xavierfoucrier** [comment]
Hi @ronilaukkarinen,

Unfortunately it's not possible at this time.
It could be done with some code and UI refactoring.

But, many things to take into considerations, like:
- Google API requests
- inbox syncing
- systray icon display
- single vs multiple notifications at a time
- etc.

So probably more than a simple option to add...

**Comment by rollecode** [comment]
OK cool. +1 for this feature then :) I'd help but C# is not my strongest suit.

**Comment by xavierfoucrier** [comment]
Tagged this as `feature`, but for sure it won't be implemented in the next release.
I really try to make the application as flexible as possible but I can't satisfy everyone's workflow.

Thanks for the idea :wink:

**Comment by davidp88** [comment]
want this feature

**Comment by xavierfoucrier** [comment]
Hi,

I am closing this, as it is requiring too much work right now to implement... but I am keeping the idea.
The application needs to be fully refactored to meet last .NET Framework requirements.

> At this point, I am also not sure we can tell Gmail API to sync two inbox at a time, because of the authentication token provided by the API, probably having a select in the application and choose the one you want to update, but both, I am not really sure.
