### ISSUE TITLE
Does it support other IMAP servers besides Gmail?

### ISSUE THREAD

**Issue by spysir** [xavierfoucrier/inbox-notifier#218]
Does it support other IMAP servers besides Gmail ? I want to receive emails from other IMAP servers

**Comment by xavierfoucrier** [comment]
Hello @spysir 👋 

Unfortunately no, **you can't configure IMAP servers inside the application** as it's relying on Gmail API. But if you want to get fresh mails from another accounts, you can connect them directly on Gmail side, this way you can also receive emails that are not tagged as `@gmail.com` with the application.

> There is no plan to add future support for other mail clients as it will require too much refactoring and implementation time.
