### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by xavierfoucrier** [xavierfoucrier/inbox-notifier#3]
Translate all the interface in English.

**Comment by Unkn0wn-MDCLXIV** [comment]
Can you make some kind of strings file?
I could translate it to german.

**Comment by xavierfoucrier** [comment]
Yes, no problem! I will do that shortly. This is a very good initiative ;-)

**Comment by xavierfoucrier** [comment]
Here is a first "draft" of all french strings present in the application. Hope this will help you translate the interface in german. I will work on this issue as soon as possible.
[translation-draft.txt](https://github.com/xavierfoucrier/gmail-notifier/files/388672/translation-draft.txt)

**Comment by xavierfoucrier** [comment]
This issue will be closed soon: I will open **a new issue** for the German language support. Thanks for your future contribution.
