### ISSUE TITLE
Automatic update check

### ISSUE THREAD

**Issue by xavierfoucrier** [xavierfoucrier/inbox-notifier#40]
Allow the user to set the application update process. Instead of have a manual update, the application could check update every weeks, months, etc. The importance of this feature is that the application must let the control to the user.

**Comment by nwoodthorpe-test1** [comment]
❤️ 💚 💙 💛 💜![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f5a4.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f499.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f494.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f468-2764-1f468.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f469-2764-1f469.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49a.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49f.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f60d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f63b.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f493.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f497.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2665.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2763.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f618.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49c.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49e.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f496.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f495.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49b.png?v7 "Logo Title Text 1")Seen by Nathaniel Woodthorpe at 00:05
