### ISSUE TITLE
Windows installer + Portable version

### ISSUE THREAD

**Issue by xavierfoucrier** [xavierfoucrier/inbox-notifier#9]
Provide a portable version of the software and a setup installer (x86/x64), based on Inno Setup program.

**Comment by Unkn0wn-MDCLXIV** [comment]
I was just about to open an Issue for that. You could also offer a portable zip version without installer (I would prefer that)

**Comment by xavierfoucrier** [comment]
@dieterhatnkleinen Thanks for your comment. I have edited the issue ;-)

**Comment by dieterhatnkleinen** [comment]
Any idea when it will be ready? I'd be glad to try it out

**Comment by xavierfoucrier** [comment]
@dieterhatnkleinen The pre-release will be delivered **soon**, may be next month. I want to implement the most features as possible before releasing a first version, this allows me to see where bugs are and the optimisations to do. You can **star the repo** on Github if you want to stay up to date. Be patient, thanks for your support ;-)

**Comment by dieterhatnkleinen** [comment]
is it dead?

**Comment by xavierfoucrier** [comment]
@dieterhatnkleinen No. I was in vacation the last two weeks, so I didn't work on the project. The dev will restart this week and an alpha version will be published when the "Message snippet" issue will be coded. Sorry for the wait :-)

**Comment by xavierfoucrier** [comment]
@dieterhatnkleinen I have published the alpha release: https://github.com/xavierfoucrier/gmail-notifier/releases/tag/v1.0-alpha. Thanks for your feedback! ;-)

**Comment by xavierfoucrier** [comment]
Installer is coded and under testing: working hard to be Windows 7 to 10 compatible.
